import React from "react";
import { View, Text, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  footerContainer: {
    position: "absolute",
    bottom: 24,
    left: 36,
    right: 36,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderTopWidth: 0.8,
    borderTopColor: "#e5e7eb",
    paddingTop: 4,
  },
  leftColumn: {
    flexDirection: "column",
  },
  systemText: {
    fontFamily: "Helvetica-Bold",
    fontSize: 6.5,
    color: "#9ca3af",
  },
  confidentialText: {
    fontFamily: "Helvetica",
    fontSize: 6.5,
    color: "#9ca3af",
    marginTop: 1,
  },
  pageNumberText: {
    fontFamily: "Helvetica-Bold",
    fontSize: 7,
    color: "#6b7280",
  },
});

export const ReportFooter: React.FC = () => {
  return (
    <View style={styles.footerContainer} fixed>
      <View style={styles.leftColumn}>
        <Text style={styles.systemText}>Generated by LCGO Information System</Text>
        <Text style={styles.confidentialText}>Confidential Student Record</Text>
      </View>
      <Text
        style={styles.pageNumberText}
        render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
      />
    </View>
  );
};
